name: acharya1
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  flutter_screenutil: ^3.2.0
  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: KumbhSans
      fonts:
        - asset: assets/fonts/KumbhSans-Bold.ttf
    - family: Bambino
      fonts:
        - asset: assets/fonts/Bambino-Bold.ttf
